spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8060

application:
    config:
      student-url: http://localhost:8050/api/v1/students
