spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8050

application:
    config:
      student-url: http://localhost:8060/api/v1/company
